---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by haoting.wang.
--- DateTime: 2018/4/4 下午4:37
---

-- 引入healthcheck模块
local hc = require "resty.upstream.healthcheck"
healthcheck = function()
    local ok, err = hc.spawn_checker {
        shm = "healthcheck",
        upstream = "test",
        type = "http",
        http_req = "GET / HTTP/1.0\r\nHost: test\r\n\r\n",
        interval = 2000,
        timeout = 5000,
        fall = 3,
        rise = 2,
        valid_statuses = {200, 302},
        concurrency = 1,
    }
    if not ok then
        ngx.log(ngx.ERR, "=====> failed to spawn health checker: ", err)
        return
    end
end
-- 调用上面定义的function
healthcheck()